name: shihogen
description: Automatic setup for Shield.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  adbnerve:
    git: https://github.com/sharpordie/adbnerve
  mvvm_plus: ^1.5.4
  netnerve:
    git: https://github.com/sharpordie/netnerve
  network_discovery: ^1.0.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  wakelock: ^0.6.2
  xml: ^6.5.0
  dio: ^5.4.0
  path_provider: ^2.1.2
  dedent: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
